Celony's Competitive Programming Collection: segment_tree< T, Combine > Class Template Reference
segment_tree< T, Combine > Class Template Reference
Iterative Segment Tree for point updates and range queries.
#include <segment_tree.hpp>
Public Member Functions
segment_tree (int n, const T &v, const Combine &combine)
segment_tree (const vector< T > &v, const T &v0, const Combine &combine)
Constructs a Segment Tree from the array.
T identity () const
Returns the default value for queries.
void update (int i, const T &v)
Updates the value at index i using the combine operation.
void set (int i, const T &v)
Sets the value at index i, replacing the current value.
T query (int l, int r) const
Queries the range [l, r) using the combine operation.
template<typename F >
int max_r (int l, F &&f)
Finds the maximum index r >= l such that f(query(l, r)) is true.
template<typename F >
int min_l (int r, F &&f)
Finds the minimum index l <= r such that f(query(l+1, r+1)) is true.
Detailed Description
template<typename T, typename Combine>
class segment_tree< T, Combine >
Iterative Segment Tree for point updates and range queries.
A versatile data structure supporting efficient range queries and point updates for any associative operation. This iterative implementation is faster and simpler than recursive versions, with excellent cache locality.
Template Parameters
T Value type.
Combine Binary associative operation (e.g., min, max, sum, gcd).
Note
Combine operation must be associative.
Supports efficient binary search on prefixes/suffixes.
Constructor & Destructor Documentation
segment_tree() [1/2]
template<typename T , typename Combine > segment_tree< T, Combine >::segment_tree (int n, const T & v, const Combine & combine) inline
segment_tree() [2/2]
template<typename T , typename Combine > segment_tree< T, Combine >::segment_tree (const vector< T > & v, const T & v0, const Combine & combine) inline
Constructs a Segment Tree from the array.
Time Complexity: \(O(N)\)
Parameters
v The array.
v0 Default value for queries.
combine Binary associative operation for combining range values.
Member Function Documentation
identity()
template<typename T , typename Combine > T segment_tree< T, Combine >::identity () const inline
Returns the default value for queries.
Time Complexity: \(O(1)\)
Referenced by heavy_light_decomposition< T, Combine >::query().
max_r()
template<typename T , typename Combine > template<typename F > int segment_tree< T, Combine >::max_r (int l, F && f) inline
Finds the maximum index r >= l such that f(query(l, r)) is true.
Time Complexity: \(O(\log N)\)
Parameters
l Left bound (inclusive).
f Predicate function that takes a query result and returns bool.
Returns
Maximum valid index r, or n if no valid range exists.
min_l()
template<typename T , typename Combine > template<typename F > int segment_tree< T, Combine >::min_l (int r, F && f) inline
Finds the minimum index l <= r such that f(query(l+1, r+1)) is true.
Time Complexity: \(O(\log N)\)
Parameters
r Right bound (inclusive).
f Predicate function that takes a query result and returns bool.
Returns
Minimum valid index l.
query()
template<typename T , typename Combine > T segment_tree< T, Combine >::query (int l, int r) const inline
Queries the range [l, r) using the combine operation.
Time Complexity: \(O(\log N)\)
Parameters
l Left bound (inclusive).
r Right bound (exclusive).
Returns
The combined result of elements [l, r).
Referenced by heavy_light_decomposition< T, Combine >::query().
set()
template<typename T , typename Combine > void segment_tree< T, Combine >::set (int i, const T & v) inline
Sets the value at index i, replacing the current value.
Time Complexity: \(O(\log N)\)
Parameters
i Zero-indexed position.
v New value.
Referenced by heavy_light_decomposition< T, Combine >::heavy_light_decomposition(), and heavy_light_decomposition< T, Combine >::set().
update()
template<typename T , typename Combine > void segment_tree< T, Combine >::update (int i, const T & v) inline
Updates the value at index i using the combine operation.
Time Complexity: \(O(\log N)\)
Parameters
i Zero-indexed position.
v Value to combine with the current element.
Referenced by heavy_light_decomposition< T, Combine >::update().
The documentation for this class was generated from the following file:
include/celony/range_query/segment_tree.hpp