Celony's Competitive Programming Collection: heavy_light_decomposition< T, Combine > Class Template Reference
heavy_light_decomposition< T, Combine > Class Template Reference
Heavy-Light Decomposition for path queries on trees.
#include <heavy_light_decomposition.hpp>
Public Member Functions
heavy_light_decomposition (const vector< vector< int > > &g, const T &v, const Combine &combine, int root=0)
Constructs HLD from a tree with uniform node values.
heavy_light_decomposition (const vector< vector< int > > &g, const vector< T > &v, const T &v0, const Combine &combine, int root=0)
Constructs HLD from a tree with specified node values.
void update (int a, const T &v)
Updates the value at a node using the combine operation.
void set (int a, const T &v)
Sets the value at a node, replacing the current value.
T query (int a, int b)
Queries the path between nodes a and b using the combine operation.
Detailed Description
template<typename T, typename Combine>
class heavy_light_decomposition< T, Combine >
Heavy-Light Decomposition for path queries on trees.
Decomposes a tree into heavy and light edges, allowing path queries and updates to be answered using a segment tree. Each root-to-node path crosses at most \(O(\log N)\) light edges, enabling efficient queries.
Template Parameters
T Value type.
Combine Binary associative operation for combining path values.
Note
Each path crosses at most log N chains.
For edge-weighted trees, store edge weights at the deeper endpoint.
Constructor & Destructor Documentation
heavy_light_decomposition() [1/2]
template<typename T , typename Combine > heavy_light_decomposition< T, Combine >::heavy_light_decomposition (const vector< vector< int > > & g, const T & v, const Combine & combine, int root = 0) inline
Constructs HLD from a tree with uniform node values.
Time Complexity: \(O(N)\)
Parameters
g Tree adjacency list.
v Initial value for all nodes.
combine Binary associative operation for path queries.
root Root of the tree (default 0).
heavy_light_decomposition() [2/2]
template<typename T , typename Combine > heavy_light_decomposition< T, Combine >::heavy_light_decomposition (const vector< vector< int > > & g, const vector< T > & v, const T & v0, const Combine & combine, int root = 0) inline
Constructs HLD from a tree with specified node values.
Time Complexity: \(O(N)\)
Parameters
g Tree adjacency list.
v Initial values for nodes.
v0 Default value for queries.
combine Binary associative operation for path queries.
root Root of the tree (default 0).
References segment_tree< T, Combine >::set().
Member Function Documentation
query()
template<typename T , typename Combine > T heavy_light_decomposition< T, Combine >::query (int a, int b) inline
Queries the path between nodes a and b using the combine operation.
Time Complexity: \(O(\log^2 N)\)
Parameters
a First node index.
b Second node index.
Returns
The combined result of all node values on the path from a to b.
References segment_tree< T, Combine >::identity(), and segment_tree< T, Combine >::query().
set()
template<typename T , typename Combine > void heavy_light_decomposition< T, Combine >::set (int a, const T & v) inline
Sets the value at a node, replacing the current value.
Time Complexity: \(O(\log N)\)
Parameters
a Node index.
v New value.
References segment_tree< T, Combine >::set().
update()
template<typename T , typename Combine > void heavy_light_decomposition< T, Combine >::update (int a, const T & v) inline
Updates the value at a node using the combine operation.
Time Complexity: \(O(\log N)\)
Parameters
a Node index.
v Value to combine with the current node value.
References segment_tree< T, Combine >::update().
The documentation for this class was generated from the following file:
include/celony/range_query/heavy_light_decomposition.hpp