Celony's Competitive Programming Collection: treap< T, Combine > Class Template Reference
treap< T, Combine > Class Template Reference
Treap class that automatically handles updating subtree values.
#include <treap.hpp>
Classes
struct node
Public Member Functions
treap (const vector< T > &v, const Combine &combine)
treap (int n, const T &v, const Combine &combine)
void split (node *root, int k, node *&l, node *&r)
Split the treap where l have first k elements and r have the rest.
void merge (node *l, node *r, node *&root)
Merges two treaps into one.
void reverse (node *root, int l, int r)
Reverses the range [l, r].
T query (node *root, int l, int r, const T &ans0)
Queries the range [l, r].
vector< T > data (node *root)
Returns the values of nodes ordered by their indices.
Static Public Member Functions
static node * new_node (const T &v)
Returns a new node with specified value.
static void destroy (node *root)
Destroy the treap.
Public Attributes
struct treap::node * root = nullptr
Detailed Description
template<typename T, typename Combine>
class treap< T, Combine >
Treap class that automatically handles updating subtree values.
Template Parameters
T Value type.
Combine Combines two subtree values with signature Fn(left, right) -> new-value.
Constructor & Destructor Documentation
treap() [1/2]
template<typename T , typename Combine > treap< T, Combine >::treap (const vector< T > & v, const Combine & combine) inline
References treap< T, Combine >::node::l, treap< T, Combine >::node::r, and treap< T, Combine >::root.
treap() [2/2]
template<typename T , typename Combine > treap< T, Combine >::treap (int n, const T & v, const Combine & combine) inline
Member Function Documentation
data()
template<typename T , typename Combine > vector< T > treap< T, Combine >::data (node * root) inline
Returns the values of nodes ordered by their indices.
Parameters
root Treap root.
References treap< T, Combine >::node::l, treap< T, Combine >::node::r, treap< T, Combine >::root, and treap< T, Combine >::node::v.
destroy()
template<typename T , typename Combine > static void treap< T, Combine >::destroy (node * root) inline static
Destroy the treap.
Parameters
root Treap root.
References treap< T, Combine >::destroy(), treap< T, Combine >::node::l, treap< T, Combine >::node::r, and treap< T, Combine >::root.
Referenced by treap< T, Combine >::destroy().
merge()
template<typename T , typename Combine > void treap< T, Combine >::merge (node * l, node * r, node *& root) inline
Merges two treaps into one.
This implemenetation assumes all left treap node values are less than right treap node.
Parameters
l Left treap root.
r Right treap root.
root Pointer reference for new root;
References treap< T, Combine >::node::l, treap< T, Combine >::merge(), treap< T, Combine >::node::p, treap< T, Combine >::node::r, and treap< T, Combine >::root.
Referenced by treap< T, Combine >::merge(), treap< T, Combine >::query(), and treap< T, Combine >::reverse().
new_node()
template<typename T , typename Combine > static node * treap< T, Combine >::new_node (const T & v) inline static
Returns a new node with specified value.
Parameters
v Node value.
query()
template<typename T , typename Combine > T treap< T, Combine >::query (node * root, int l, int r, const T & ans0) inline
Queries the range [l, r].
Parameters
root Treap root.
l Left boundary.
r Right boundary.
ans0 Default answer for nodes.
References treap< T, Combine >::node::ans, treap< T, Combine >::merge(), treap< T, Combine >::root, and treap< T, Combine >::split().
reverse()
template<typename T , typename Combine > void treap< T, Combine >::reverse (node * root, int l, int r) inline
Reverses the range [l, r].
Parameters
root Treap root.
l Left boundary.
r Right boundary.
References treap< T, Combine >::merge(), treap< T, Combine >::node::rev, treap< T, Combine >::root, and treap< T, Combine >::split().
split()
template<typename T , typename Combine > void treap< T, Combine >::split (node * root, int k, node *& l, node *& r) inline
Split the treap where l have first k elements and r have the rest.
Parameters
root Root of treap.
k Number of elements for l.
l Pointer reference for left root.
r Pointer reference for right root.
References treap< T, Combine >::node::l, treap< T, Combine >::node::r, treap< T, Combine >::root, and treap< T, Combine >::split().
Referenced by treap< T, Combine >::query(), treap< T, Combine >::reverse(), and treap< T, Combine >::split().
Member Data Documentation
root
template<typename T , typename Combine > struct treap::node * treap< T, Combine >::root = nullptr
Referenced by treap< T, Combine >::data(), treap< T, Combine >::destroy(), treap< T, Combine >::merge(), treap< T, Combine >::query(), treap< T, Combine >::reverse(), treap< T, Combine >::split(), and treap< T, Combine >::treap().
The documentation for this class was generated from the following file:
include/celony/range_query/treap.hpp