Celony's Competitive Programming Collection: union_find< F > Class Template Reference
union_find< F > Class Template Reference
Disjoint Set Union (DSU) / Union-Find data structure with custom merge callback.
#include <union_find.hpp>
Public Member Functions
union_find (int n, const F &f)
Constructs a Union-Find structure with n elements.
int find (int i)
Finds the leader of the component containing element i.
int size (int i)
Returns the size of the component containing element i.
int components () const
Returns the current number of disjoint components.
bool unite (int i, int j)
Unites the components containing elements i and j.
Detailed Description
template<typename F>
class union_find< F >
Disjoint Set Union (DSU) / Union-Find data structure with custom merge callback.
Supports efficient union and find operations with path compression. Uses union-by-size for optimization and provides a callback mechanism to execute custom logic when merging components.
Template Parameters
F Merge functor type with signature void(int parent, int child). Called when merging components, where parent is the leader that absorbs the child component.
Note
\(\alpha(N)\) is the inverse Ackermann function, effectively constant (< 5) for all practical values of N.
Constructor & Destructor Documentation
union_find()
template<typename F > union_find< F >::union_find (int n, const F & f) inline
Constructs a Union-Find structure with n elements.
Parameters
n Number of elements (0 to n-1).
f Merge callback function with signature void(int parent, int child).
Member Function Documentation
components()
template<typename F > int union_find< F >::components () const inline
Returns the current number of disjoint components.
Time Complexity: \(O(1)\)
Returns
The number of connected components.
find()
template<typename F > int union_find< F >::find (int i) inline
Finds the leader of the component containing element i.
Time Complexity: \(O(\alpha(N))\) amortized
Parameters
i Element index.
Returns
The leader (representative) of the component.
References union_find< F >::find().
Referenced by union_find< F >::find(), union_find< F >::size(), and union_find< F >::unite().
size()
template<typename F > int union_find< F >::size (int i) inline
Returns the size of the component containing element i.
Time Complexity: \(O(\alpha(N))\) amortized
Parameters
i Element index.
Returns
The number of elements in the component.
References union_find< F >::find().
unite()
template<typename F > bool union_find< F >::unite (int i, int j) inline
Unites the components containing elements i and j.
Time Complexity: \(O(\alpha(N))\) amortized
Parameters
i First element index.
j Second element index.
Returns
True if the elements were in different components and were merged, false otherwise.
References union_find< F >::find().
The documentation for this class was generated from the following file:
include/celony/graph/union_find.hpp